version: "2"

plugins:
  # lints js and ts
  eslint:
    enabled: true
  # lints scss
  stylelint:
    enabled: true
  # finds similar code blocks
  duplication:
    enabled: true
  # highlights strings TODO, FIXME, HACK, XXX, and BUG
  fixme:
    enabled: true

checks:
  argument-count:
    enabled: true
  complex-logic:
    enabled: true
  file-lines:
    enabled: true
  method-complexity:
    enabled: true
  method-count:
    enabled: true
  method-lines:
    enabled: true
  nested-control-flow:
    enabled: true
  return-statements:
    enabled: true
  similar-code:
    enabled: true
  identical-code:
    enabled: true

exclude_patterns:
  - "node_modules/*"
  - "scripts/*"
  - "www/*"
  - "documentation/*"
  - "plugins/*"
  - "platforms/*"
  - "resources/*"
