phonegap plugin add https://github.com/apache/cordova-plugin-inappbrowser#r1.0.1
phonegap plugin add https://github.com/apache/cordova-plugin-splashscreen
phonegap plugin add https://github.com/apache/cordova-plugin-dialogs.git
phonegap plugin add https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin.git
phonegap plugin add https://github.com/apache/cordova-plugin-device.git
phonegap plugin add https://github.com/apache/cordova-plugin-network-information.git
phonegap plugin add https://github.com/Initsogar/cordova-webintent.git
phonegap plugin add https://github.com/apache/cordova-plugin-file.git#r1.3.3
phonegap plugin add https://github.com/apache/cordova-plugin-file-transfer.git#r0.5.0
phonegap plugin add https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git