# This workflow will do a clean install of node dependencies, build the source code and 

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: git submodule init
    - run: git submodule update
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run compodoc
    - run: bash ./deploy.sh
    
env:
  GH_REF: github.com/University-of-Potsdam-MM/Mobile.UP.git
